[project]
name = "reyapi"
version = "1.1.35"
description = "API method set."
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
keywords = ["rey", "reyxbo", "api", "backend", "async", "asynchrouous"]
authors = [
    {name = "Rey", email = "reyxbo@163.com"}
]
dependencies = [
    "reykit"
]

[project.urls]
homepage = "https://github.com/reyxbo/reyapi/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = [
    "python-multipart",
    "reyapi",
    "sqlalchemy",
    "sqlmodel",
    "uvicorn[standard]"
]
